openapi: "3.0.3"

info:
  title: "Sample API"
  description: |
    # aaaaa
    - aaaaa
    - bbbbb

  version: "1.0.1"

servers:
  - url: "http://localhost:{port}"
    description: "Local development"
    variables:
      port:
        enum: ["3000", "8080"]
        default: "3000"
  - url: "https:/it1.test.com"
    description: "Integration Test"
  - url: "https://stg.test.com"
    description: "Staging"
  - url: "https://api.test.com"
    description: "Production"
paths:
  "/shops/{shopId}/reviews":
    get:
      summary: "Get shop reviews"
      description: "(desc) Get shop reviews"
      tags: ["shops"]
      deprecated: false
      parameters:
        - name: shopId
          in: path
          required: true
          schema: {type: string}
      responses:
        "200":
          description: "Succcess"
    post:
      summary: "Create review"
      tags: ["shops"]
      deprecated: false
      parameters:
        - name: shopId
          in: path
          required: true
          schema: {type: string}
          example: "abcdefg"
        - name: X-Api-Key
          in: header
          description: "request user's identifier"
          schema: {type: string}
          example: "XXXX-XXXX-XXXX-XXXX"
        - name: token
          in: cookie
          description: "One time token"
          schema: {type: string}
          example: "XXXX-XXXX-XXXX-XXXX"
      responses:
        "201":
          description: "Succcess"



components:
  schemas:
    SampleInt32:
      type: integer
      format: int32
    SampleDateString:
      type: string
      format: date