openapi: "3.0.3"

info:
  title: "Sample API"
  description: |
    # aaaaa
    - aaaaa
    - bbbbb

  version: "1.0.1"

servers: []

paths:
  {}

components:
  schemas:
    SampleInt32:
      type: integer
      format: int32
    SampleDateString:
      type: string
      format: date