openapi: "3.0.3"

info:
  title: "Sample API"
  description: |
    # aaaaa
    - aaaaa
    - bbbbb

  version: "1.0.1"

servers:
  - url: "http://localhost:{port}"
    description: "Local development"
    variables:
      port:
        enum: ["3000", "8080"]
        default: "3000"
  - url: "https:/it1.test.com"
    description: "Integration Test"
  - url: "https://stg.test.com"
    description: "Staging"
  - url: "https://api.test.com"
    description: "Production"
paths:
  "/shops/{shopId}/reviews":
    get:
      summary: "Get shop reviews"
      description: "(desc) Get shop reviews"
      tags: ["shops"]
      deprecated: false
      parameters:
        - name: shopId
          in: path
          required: true
          schema: {type: string}
      responses:
        "200":
          description: "Succcess"
    post:
      summary: "Create review"
      tags: ["shops"]
      deprecated: false
      parameters:
        - name: shopId
          in: path
          required: true
          schema: {type: string}
          example: "abcdefg"
        - name: X-Api-Key
          in: header
          description: "request user's identifier"
          schema: {type: string}
          example: "XXXX-XXXX-XXXX-XXXX"
        - name: token
          in: cookie
          description: "One time token"
          schema: {type: string}
          example: "XXXX-XXXX-XXXX-XXXX"
      requestBody:
        description: "contents of review"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                score: {type: integer, example: 3}
                comment: {type: string, example: "delicious"}
      responses:
        "201":
          description: "Succcess"
          headers:
            location:
              description: "New URL of created review"
              schema: {type: string, format: url}
        "400":
          description: "Client side error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: {type: string}
                  type: {type: string}
                  message: {type: string}
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field: {type: string}
                        code: {type: string}



components:
  schemas:
    SampleInt32:
      type: integer
      format: int32
    SampleDateString:
      type: string
      format: date