openapi: "3.0.3"

info:
  title: "Sample API"
  description: |
    # aaaaa
    - aaaaa
    - bbbbb

  version: "1.0.1"

servers:
  - url: "http://localhost:{port}"
    description: "Local development"
    variables:
      port:
        enum: ["3000", "8080"]
        default: "3000"
  - url: "https:/it1.test.com"
    description: "Integration Test"
  - url: "https://stg.test.com"
    description: "Staging"
  - url: "https://api.test.com"
    description: "Production"
paths:
  {}

components:
  schemas:
    SampleInt32:
      type: integer
      format: int32
    SampleDateString:
      type: string
      format: date